FROM mysql:5
# only needed if creating initial DB
#RUN apt-get update && apt-get install -y wget
#RUN wget -O /docker-entrypoint-initdb.d/10-schema.sql \
#     https://raw.githubusercontent.com/cBioPortal/cbioportal/v1.13.1/db-scripts/src/main/resources/cgds.sql && \
#    wget -O /docker-entrypoint-initdb.d/20-seed-db.sql.gz \
#     https://github.com/cBioPortal/datahub/raw/master/seedDB/seed-cbioportal_hg19_v2.6.0.sql.gz
